// Generated by CoffeeScript 1.9.3
(function() {
  describe("A failing test", function() {
    return it("should fail", function() {
      return expect(false).toBe(true);
    });
  });

  describe("A passing test", function() {
    return it("should pass", function() {
      return expect(true).toBe(true);
    });
  });

}).call(this);

//# sourceMappingURL=test_test.spec.js.map
